const translations = {
    en: {
        hero_title: "PROTECT YOUR<br>HEART TODAY",
        hero_intro: "Understand your cardiovascular health through a personalized assessment based on your lifestyle, medical history, and daily habits.",
        badge_time: "⏱ Under 3 minutes",
        badge_prep: "🩺 No medical prep needed",
        badge_privacy: "🔒 100% confidential & free",
        cta_button: "Check Your Risk →",
        footer_privacy: "🔒 Your privacy matters to us. All responses are confidential and are never shared, sold, or disclosed to third parties.",
        footer_disclaimer: "This tool is for educational purposes only and does not replace professional medical diagnosis or treatment.",
        card1Title: "❤️ Assess Your Risk",
        card1Text: "Complete a quick evidence-based assessment in under 3 minutes.",
        card2Title: "📊 Personalized Results",
        card2Text: "Learn which lifestyle factors contribute most to your cardiovascular risk.",
        card3Title: "💡 Prevention Tips",
        card3Text: "Receive practical recommendations for improving long-term heart health.",
        sneakTitle: "See What You'll Get",
        sneakRisk: "🟠 Moderate Risk",
        sneakNote: "*Example only — your real results will be based on your own answers.",
        sneakItem1: "❤️ Your estimated cardiovascular health",
        sneakItem2: "📊 Which lifestyle factors matter most for you",
        sneakItem3: "🫀 Your risk level for conditions like heart failure <br> & diabetic cardiomyopathy",
        sneakItem4: "💡 Personalized prevention tips based on your answers",
          // --- oxygen/pressure/sugar/bmi/smoking tags ---
        oxygenTag: "Oxygen Level",
        pressureTag: "Blood Pressure",
        sugarTag: "Blood Sugar",
        bmiTag: "BMI",
        smokingTag: "Smoking",

        // --- footer (모든 페이지 공통) ---
        footer_privacy: "🔒 Your privacy matters to us. All responses are confidential and are never shared, sold, or disclosed to third parties.",
        footer_disclaimer: "This tool is for educational purposes only and does not replace professional medical diagnosis or treatment.",
        footer_contact: "📧 contact@heartguard.app",

        // --- about us page ---
                aboutBadge: "❤️ About HeartGuard",
        aboutH1: "Understand Your Heart Before You Begin",
        aboutIntro: "HeartGuard was created to help people recognize cardiovascular risk before it becomes a crisis. Heart disease often develops silently for years, and by the time symptoms appear, significant damage may already be done. Our goal is simple: give people a quick, private way to understand their own risk factors and take action early.",
        whyBuiltTitle: "🎯 Why We Built This",
        whyBuiltText: "Most people underestimate their cardiovascular risk because it rarely announces itself. We built HeartGuard to close that gap — not by diagnosing disease, but by helping you see which everyday habits are quietly shaping your heart health, and what you can do about it starting today.",
        mexicoFocusTitle: "🇲🇽 Focused on Mexico",
        mexicoFocusText: "Mexico has one of the highest rates of diabetes and sugar-sweetened beverage consumption in the world, and diabetes is closely linked to serious heart complications like diabetic cardiomyopathy. We built HeartGuard with this reality in mind — using everyday habits like diet, sugary drinks, and physical activity as a starting point for a conversation people can have with themselves, and with their doctors.",
        aboutCard1Title: "🩸 Diabetes & Blood Sugar",
        aboutCard1Text: "Persistently high blood sugar can damage blood vessels and heart muscle, increasing the risk of cardiovascular disease.",
        aboutCard2Title: "❤️ Many Risk Factors Work Together",
        aboutCard2Text: "High blood pressure, smoking, unhealthy diet, lack of exercise, obesity, and family history all contribute to heart disease.",
        aboutCard3Title: "⚠️ Early Prevention Matters",
        aboutCard3Text: "Understanding your personal risk can help you make healthier lifestyle choices and know when to seek medical advice.",
        aboutNotice: "💙 This assessment is designed for educational purposes only and does not replace professional medical diagnosis or treatment.",
        aboutButton: "Continue to Assessment →",

        /// assessment page
                genderMale: "Male",
        genderFemale: "Female",
        assessmentH1: "🫀 HeartGuard Assessment",
        q1Title: "1. What is your gender?",
        q1Ethnicity: "Ethnicity (optional, select all that apply)",
        ethnicityHispanic: "Hispanic / Latino",
        ethnicityAsian: "Asian",
        ethnicityWhite: "White",
        ethnicityBlack: "Black",
        ethnicityOther: "Other",
        ethnicityNa: "Prefer not to say",
        q2Title: "2. What is your age group?",
        under30Option: "Under 30",
        age30Option: "30–39",
        age40Option: "40–49",
        age50Option: "50–59",
        age60Option: "60–69",
        age70Option: "70+",
        q3Title: "3. Height & Weight",
        heightLabel: "Height (cm)",
        weightLabel: "Weight (kg)",
        bmiLabel: "Your BMI:",
        q4Title: "4. Have you been diagnosed with diabetes?",
        type1Option: "Yes, Type 1",
        type2Option: "Yes, Type 2",
        prediabetesOption: "Prediabetes",
        noDiabetesOption: "No",
        q5Title: "5. How long have you been diagnosed?",
        lt5Option: "Less than 5 years",
        fiveTenOption: "5–10 years",
        gt10Option: "More than 10 years",
        naDurationOption: "Not applicable",
        q6Title: "6. Do you take any medications or use glucose trackers?",
        q6Tip: "Select all that apply.",
        treatmentNone: "No treatment",
        treatmentOral: "Oral medication",
        treatmentInsulin: "Insulin injections",
        treatmentCgm: "Continuous Glucose Monitor (CGM)",
        treatmentPump: "Insulin pump",
        treatmentNa: "Not applicable (I don't have diabetes)",
        q7Title: "7. How many days per week do you engage in intense workouts?",
        exercise5Option: "5–7 days",
        exercise3Option: "3–4 days",
        exercise1Option: "1–2 days",
        exercise0Option: "Rarely or never",
        q8Title: "8. How often do you drink sugary beverages?",
        sugarNeverOption: "Never",
        sugar12Option: "1–2 times per week",
        sugar36Option: "3–6 times per week",
        sugarDailyOption: "Once a day",
        sugar3DailyOption: "More than three times a day",
        q9Title: "9. Do you currently smoke or use tobacco products?",
        smokingNeverOption: "Never",
        smokingFormerOption: "Former smoker",
        smokingSometimesOption: "Occasionally",
        smokingDailyOption: "Daily",
        q10Title: "10. Do you have high blood pressure?",
        bpYesOption: "Yes",
        bpNoOption: "No",
        bpUnsureOption: "Unsure",
        q11Title: "11. Do you get short of breath regularly?",
        breathYesOption: "Yes",
        breathNoOption: "No",
        q12Title: "12. Have you noticed swelling in your ankles or feet?",
        swellingTip: "Try pressing your skin gently for 5 seconds. If an indentation remains briefly after you remove your thumb, this may be a sign of swelling.",
        swellingYesOption: "Yes",
        swellingNoOption: "No",
        swellingBanner: "🚨 Swelling in the ankles or feet can be a sign of fluid retention related to heart function. We strongly recommend seeing a doctor soon to have this checked.",
        q13Title: "13. Has a doctor ever told you that you have high cholesterol?",
        cholesterolYesOption: "Yes",
        cholesterolNoOption: "No",
        q14Title: "14. Has an immediate family member (parent or sibling) been diagnosed with cardiovascular disease before age 55 (male) or age 65 (female)?",
        familyYesOption: "Yes",
        familyNoOption: "No",
        familyUnsureOption: "Unsure",
        familyBanner: "ℹ️ Family history plays a significant role in cardiovascular risk. If you're unsure, it's worth asking a parent or checking with your doctor.",
        q15Title: "15. During your typical school or work day, do you spend most of your time:",
        activitySittingOption: "Mostly sitting",
        activityStandingOption: "Mostly standing",
        activityPhysicalOption: "Doing physically demanding activities",
        q16Title: "16. How would you describe your typical diet?",
        dietHomecooked: "I eat home-cooked meals (vegetables, beans, grilled chicken or fish) almost every day, rarely eating out",
        dietMostlyhome: "I mostly eat home-cooked meals, but eat out or order food 1–2 times a week",
        dietEatingout: "I eat out, order delivery, or eat street food (tacos, tortas, pizza) 3–5 times a week",
        dietProcessed: "I rarely cook at home — most days I eat fried, processed, or sugary foods",
        q17Title: "When was your last hospital check-up?",
        checkupLt1: "Within the last year",
        checkup1to2: "1–2 years ago",
        checkupGt2: "More than 2 years ago",
        checkupNever: "I have never had one",
        prevBtn: "← Previous",
        nextBtn: "Next →",

    },
    es: {
        hero_title: "PROTEGE TU<br>CORAZÓN HOY",
        hero_intro: "Comprende tu salud cardiovascular a través de una evaluación personalizada basada en tu estilo de vida, historial médico y hábitos diarios.",
        badge_time: "⏱ Menos de 3 minutos",
        badge_prep: "🩺 Sin preparación médica",
        badge_privacy: "🔒 100% confidencial y gratis",
        cta_button: "Revisa Tu Riesgo →",
        footer_privacy: "🔒 Tu privacidad es importante para nosotros. Todas las respuestas son confidenciales y nunca se comparten, venden ni divulgan a terceros.",
        footer_disclaimer: "Esta herramienta es solo para fines educativos y no reemplaza el diagnóstico o tratamiento médico profesional.",
        card1Title: "❤️ Evalúa Tu Riesgo",
        card1Text: "Completa una evaluación rápida basada en evidencia en menos de 3 minutos.",
        card2Title: "📊 Resultados Personalizados",
        card2Text: "Descubre qué factores de estilo de vida contribuyen más a tu riesgo cardiovascular.",
        card3Title: "💡 Consejos de Prevención",
        card3Text: "Recibe recomendaciones prácticas para mejorar la salud del corazón a largo plazo.",
        sneakTitle: "Mira Lo Que Obtendrás",
        sneakRisk: "🟠 Riesgo Moderado",
        sneakNote: "*Solo un ejemplo — tus resultados reales se basarán en tus propias respuestas.",
        sneakItem1: "❤️ Tu salud cardiovascular estimada",
        sneakItem2: "📊 Qué factores de estilo de vida importan más para ti",
        sneakItem3: "🫀 Tu nivel de riesgo de condiciones como insuficiencia cardíaca <br> y cardiomiopatía diabética",
        sneakItem4: "💡 Consejos de prevención personalizados según tus respuestas",

        oxygenTag: "Nivel de Oxígeno",
        pressureTag: "Presión Arterial",
        sugarTag: "Azúcar en Sangre",
        bmiTag: "IMC",
        smokingTag: "Tabaquismo",

        footer_privacy: "🔒 Tu privacidad es importante para nosotros. Todas las respuestas son confidenciales y nunca se comparten, venden ni divulgan a terceros.",
        footer_disclaimer: "Esta herramienta es solo para fines educativos y no reemplaza el diagnóstico o tratamiento médico profesional.",
        footer_contact: "📧 contact@heartguard.app",

        ///about us page

                aboutBadge: "❤️ Sobre HeartGuard",
        aboutH1: "Comprende Tu Corazón Antes de Comenzar",
        aboutIntro: "HeartGuard fue creado para ayudar a las personas a reconocer el riesgo cardiovascular antes de que se convierta en una crisis. Las enfermedades cardíacas a menudo se desarrollan silenciosamente durante años, y cuando aparecen los síntomas, el daño ya puede ser significativo. Nuestro objetivo es simple: dar a las personas una forma rápida y privada de entender sus propios factores de riesgo y actuar a tiempo.",
        whyBuiltTitle: "🎯 Por Qué Creamos Esto",
        whyBuiltText: "La mayoría de las personas subestiman su riesgo cardiovascular porque rara vez se manifiesta. Creamos HeartGuard para cerrar esa brecha — no para diagnosticar enfermedades, sino para ayudarte a ver qué hábitos cotidianos están afectando silenciosamente la salud de tu corazón, y qué puedes hacer al respecto desde hoy.",
        mexicoFocusTitle: "🇲🇽 Enfocado en México",
        mexicoFocusText: "México tiene una de las tasas más altas de diabetes y consumo de bebidas azucaradas en el mundo, y la diabetes está estrechamente relacionada con complicaciones cardíacas graves como la cardiomiopatía diabética. Creamos HeartGuard pensando en esta realidad — usando hábitos cotidianos como la dieta, las bebidas azucaradas y la actividad física como punto de partida para una conversación que las personas pueden tener consigo mismas y con sus médicos.",
        aboutCard1Title: "🩸 Diabetes y Azúcar en Sangre",
        aboutCard1Text: "El azúcar en sangre persistentemente alto puede dañar los vasos sanguíneos y el músculo cardíaco, aumentando el riesgo de enfermedad cardiovascular.",
        aboutCard2Title: "❤️ Muchos Factores de Riesgo Actúan Juntos",
        aboutCard2Text: "La presión arterial alta, el tabaquismo, una dieta poco saludable, la falta de ejercicio, la obesidad y los antecedentes familiares contribuyen a la enfermedad cardíaca.",
        aboutCard3Title: "⚠️ La Prevención Temprana Importa",
        aboutCard3Text: "Comprender tu riesgo personal puede ayudarte a tomar decisiones de estilo de vida más saludables y saber cuándo buscar atención médica.",
        aboutNotice: "💙 Esta evaluación es solo para fines educativos y no reemplaza el diagnóstico o tratamiento médico profesional.",
        aboutButton: "Continuar a la Evaluación →",

        /// assessment page
                genderMale: "Masculino",
        genderFemale: "Femenino",
        assessmentH1: "🫀 Evaluación HeartGuard",
        q1Title: "1. ¿Cuál es tu género?",
        q1Ethnicity: "Etnicidad (opcional, selecciona todas las que apliquen)",
        ethnicityHispanic: "Hispánico / Latino",
        ethnicityAsian: "Asiático",
        ethnicityWhite: "Blanco",
        ethnicityBlack: "Negro",
        ethnicityOther: "Otro",
        ethnicityNa: "Prefiero no decir",
        q2Title: "2. ¿Cuál es tu grupo de edad?",
        under30Option: "Menos de 30",
        age30Option: "30–39",
        age40Option: "40–49",
        age50Option: "50–59",
        age60Option: "60–69",
        age70Option: "70+",
        q3Title: "3. Altura y Peso",
        heightLabel: "Altura (cm)",
        weightLabel: "Peso (kg)",
        bmiLabel: "Tu IMC:",
        q4Title: "4. ¿Te han diagnosticado diabetes?",
        type1Option: "Sí, Tipo 1",
        type2Option: "Sí, Tipo 2",
        prediabetesOption: "Prediabetes",
        noDiabetesOption: "No",
        q5Title: "5. ¿Hace cuánto te diagnosticaron?",
        lt5Option: "Menos de 5 años",
        fiveTenOption: "5–10 años",
        gt10Option: "Más de 10 años",
        naDurationOption: "No aplica",
        q6Title: "6. ¿Tomas medicamentos o usas monitores de glucosa?",
        q6Tip: "Selecciona todas las que apliquen.",
        treatmentNone: "Sin tratamiento",
        treatmentOral: "Medicamento oral",
        treatmentInsulin: "Inyecciones de insulina",
        treatmentCgm: "Monitor Continuo de Glucosa (CGM)",
        treatmentPump: "Bomba de insulina",
        treatmentNa: "No aplica (no tengo diabetes)",
        q7Title: "7. ¿Cuántos días a la semana haces ejercicio intenso?",
        exercise5Option: "5–7 días",
        exercise3Option: "3–4 días",
        exercise1Option: "1–2 días",
        exercise0Option: "Casi nunca",
        q8Title: "8. ¿Con qué frecuencia tomas bebidas azucaradas?",
        sugarNeverOption: "Nunca",
        sugar12Option: "1–2 veces por semana",
        sugar36Option: "3–6 veces por semana",
        sugarDailyOption: "Una vez al día",
        sugar3DailyOption: "Más de tres veces al día",
        q9Title: "9. ¿Fumas o usas productos de tabaco?",
        smokingNeverOption: "Nunca",
        smokingFormerOption: "Exfumador",
        smokingSometimesOption: "Ocasionalmente",
        smokingDailyOption: "Diariamente",
        q10Title: "10. ¿Tienes presión arterial alta?",
        bpYesOption: "Sí",
        bpNoOption: "No",
        bpUnsureOption: "No estoy seguro",
        q11Title: "11. ¿Te falta el aire con regularidad?",
        breathYesOption: "Sí",
        breathNoOption: "No",
        q12Title: "12. ¿Has notado hinchazón en tobillos o pies?",
        swellingTip: "Intenta presionar suavemente tu piel durante 5 segundos. Si queda una marca hundida brevemente después de retirar el dedo, esto puede ser señal de hinchazón.",
        swellingYesOption: "Sí",
        swellingNoOption: "No",
        swellingBanner: "🚨 La hinchazón en tobillos o pies puede ser señal de retención de líquidos relacionada con la función cardíaca. Recomendamos encarecidamente consultar a un médico pronto.",
        q13Title: "13. ¿Un médico te ha dicho alguna vez que tienes colesterol alto?",
        cholesterolYesOption: "Sí",
        cholesterolNoOption: "No",
        q14Title: "14. ¿Tienes un familiar directo (padre, madre o hermano/a) que ha sido diagnosticado con enfermedad cardiovascular antes de los 55 años (hombres) o 65 años (mujeres)?",
        familyYesOption: "Sí",
        familyNoOption: "No",
        familyUnsureOption: "No estoy seguro",
        familyBanner: "ℹ️ Los antecedentes familiares juegan un papel importante en el riesgo cardiovascular. Si no estás seguro, vale la pena preguntarle a un familiar o consultarlo con tu médico.",
        q15Title: "15. Durante tu día típico de escuela o trabajo, ¿en qué postura pasas más tiempo?",
        activitySittingOption: "Mayormente sentado",
        activityStandingOption: "Mayormente de pie",
        activityPhysicalOption: "Actividades físicamente demandantes",
        q16Title: "16. ¿Cómo describirías tu dieta típica?",
        dietHomecooked: "Como comida casera (verduras, frijoles, pollo o pescado a la parrilla) casi todos los días, rara vez como fuera",
        dietMostlyhome: "Mayormente de comida casera, pero aveces fuera o pido comida 1–2 veces por semana",
        dietEatingout: "Como fuera frecuentemente, pido a domicilio o como comida callejera (tacos, tortas, pizza) 3–5 veces por semana",
        dietProcessed: "Rara vez cocino en casa — la mayoría de los días como comida frita, procesada o azucarada",
        q17Title: "¿Cuándo fue tu último evaluación médico?",
        checkupLt1: "En el último año",
        checkup1to2: "Hace 1–2 años",
        checkupGt2: "Hace más de 2 años",
        checkupNever: "Nunca he tenido uno",
        prevBtn: "← Anterior",
        nextBtn: "Siguiente →",
    }
};

function setLanguage(lang) {

    document.querySelectorAll("[data-i18n]").forEach(el => {
        const key = el.getAttribute("data-i18n");
        if (translations[lang] && translations[lang][key]) {
            el.innerHTML = translations[lang][key];
        }
    });

    localStorage.setItem("heartguardLang", lang);

    document.querySelectorAll(".lang-btn").forEach(btn => {
        btn.classList.toggle("active", btn.dataset.lang === lang);
    });
}

document.addEventListener("DOMContentLoaded", () => {
    const saved = localStorage.getItem("heartguardLang") || "en";
    setLanguage(saved);
});
